pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                label 'slave1'
            }
            steps {
                sh 'sleep 10'
            }
        }

        stage('Test') {
            agent any
            steps {
                sh '''
                    #!/bin/bash
                    ls -lrt
                    sleep 10
                '''
            }
        }

    }
}