pipeline {
    agent none
    environment {
        TEST = "test_value"
        TEST1 = "test_value1"
    }
    stages {
        stage('Build') {
            agent {
                label 'slave1'
            }
            steps {
                sh '''
                    echo $TEST $TEST1
                    sleep 5
                '''
            }
        }

        stage('Test') {
            agent any
            steps {
                sh '''
                    #!/bin/bash
                    echo $TEST $TEST1
                    sleep 5
                '''
            }
        }

    }
}